config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'profile/:id', to: 'pages#profile', as:'profile'
  resources :socks do
    resources :transactions, only: [:show, :new, :create]
  end
  root to: 'socks#index'
  get "profile/:id/reviews/new", to: "reviews#new", as:"new_review"
  post "profile/:id", to: "reviews#create", as:"user_reviews"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sock.rb
class Sock < ApplicationRecord

  SOCK_TYPE = ["Over knee", "Knee high", "Over calf", "Mid-calf", "Quarter", "Low cut", "Extra low cut", "Invisible", "Toe cover"].freeze
  SOCK_PATTERN = ["Solid", "Striped", "Shape", "Polka dots", "Other"].freeze
  SEASON = ["Spring", "Summer", "Autumn", "Winter"].freeze
  SIZES = ["36-41", "42-46", "47-51"].freeze
  COLOR = ["Apricot", "Beige", "Black", "Blue", "Brown", "Cyan", "Green", "Grey", "Lavender", "Lime", "Magenta", "Maroon", "Mint", "Navy", "Olive", "Orange", "Pink", "Purple", "Red", "Teal", "White", "Yellow"].freeze



  # for cloudinary
  mount_uploader :photo, PhotoUploader

  include PgSearch
  pg_search_scope :search_by_color_and_title,
    against: [:title, :color, :pattern, :season],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

    pg_search_scope :search_by_filters,
    against: [:color, :sock_type, :pattern, :season],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  belongs_to :user

  validates :brand, presence: true
  validates :sock_type, presence: true
  validates :title, presence: true
  validates :color, inclusion: { in: COLOR }, presence: true
  validates :price, presence: true, numericality: true
  validates :pattern, inclusion: { in: SOCK_PATTERN }, presence: true
  validates :size, inclusion: { in: SIZES }, presence: true
  validates :description, presence: true
  # validates :sock_type, inclusion: { in: ["Over the knee", "Knee high", "Over the calf/Executive", "Mid-calf/Crew", "Quarter/Anklets", "Ped/Low cut", "Liner/Extra low cut", "Invisible/No-show", "Toe cover/Mute"] }, allow_blank: true
  validates :season, inclusion: { in: SEASON }, presence: true

end

app/controllers/socks_controller.rb
class SocksController < ApplicationController
  before_action :set_sock, only: [:show, :edit, :update, :destroy]
  # skip_after_action :verify_policy_scoped
  skip_before_action :authenticate_user!, only: [:show]
  before_action :instance_user, only: [:index]

  def index
    if params[:search].present?
      @socks = policy_scope(Sock).search_by_color_and_title(params[:search])
    elsif params[:filter_color].present? || params[:filter_sock_type].present? || params[:filter_sock_pattern].present? || params[:filter_season].present?
      search_term = params[:filter_color] + ' ' + params[:filter_sock_type] + ' ' + params[:filter_sock_pattern] + ' ' + params[:filter_season]
      @socks = policy_scope(Sock).search_by_filters(search_term)
    else
      @socks = policy_scope(Sock)
    end
    respond_to do |format|

      format.html { render 'socks/index' }
      format.js
    end
  end

  def show
    @user = @sock.user
    @ids = get_reviewer
    @user = @sock.user
     if @user.latitude != nil && @user.longitude != nil
      @markers = [
        lat: @user.latitude,
        lng: @user.longitude,
        image_url: helpers.asset_url('sock-marker.png')
      ]
    else
      @markers = []
    end
  end

  def new
    @sock = Sock.new
    authorize @sock
  end

  def create
    @sock = Sock.new(sock_params)
    @sock.user = current_user
    authorize @sock
    if @sock.save
      redirect_to sock_path(@sock)
    else
      render :new
    end
  end

  def edit
    authorize @sock
  end

  def update
    authorize @sock
    @sock.update(sock_params)
    redirect_to sock_path(@sock)
  end

  def destroy
    @sock.destroy
    redirect_to socks_path
  end

  private

  def instance_user
    @instance_user = User.new
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def set_sock
    @sock = Sock.find(params[:id])
  end

  def sock_params
    params.require(:sock).permit(:title, :description, :color, :pattern, :size, :sock_type, :brand, :season, :age, :price, :photo)
  end

  def filtering_params(params)
    params.slice(:color, :size, :sock_type, :brand, :season, :age, :price)
  end

  def get_reviewer
    ids = []
    @user.reviews.each do |review|
      ids << review.review_giver_id
    end
    return ids
  end
end

app/views/socks/_cards_container.html.erb
<div class="cards">
  <% socks.each do |sock| %>
    <% if sock.bought == false %>
      <div class="card-sock">
        <% if sock.photo.file.nil? %>
        <%= link_to sock_path(sock), class: "card-trip" do  %>
          <%= image_tag 'demo.png', crop: :fill, height: 220; %>
          <% end %>
        <% else %>
        <%= link_to sock_path(sock), class: "card-trip" do  %>
          <%= cl_image_tag sock.photo, crop: :fill, height: 220; %>
          <% end %>
        <% end %>
        <div class="card-sock-infos">
          <div>
            <h2><%= link_to sock.title, sock_path(sock) %></h2>
            <p> <%= sock.description %></p>
          </div>
          <h2 class="card-sock-pricing"> $<%= sock.price %></h2>
          <%= link_to profile_path(sock.user) do  %>
            <% if sock.user.photo.url.nil? %>
              <%= image_tag 'avatar_ifnil.png', height: 40, width: 40, crop: :fill, class:'card-sock-user avatar-bordered' %>
            <% else %>
              <%= cl_image_tag sock.user.photo, height: 40, width: 40, crop: :fill, class:'card-sock-user avatar-bordered'  %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
</div>

app/views/socks/_form.html.erb
<div class="container">
  <%= simple_form_for @sock do |s| %>
  <div class="row">
    <div class="col-12 col-md-6"> <%= s.input :title, label: "Name your sock" %></div>
    <div class="col-12 col-md-6"> <%= s.input :color, collection: Sock::COLOR %>  </div>
  <div class="w-100"></div>
    <div class="col-12 col-md-6"> <%= s.input :description, label: "Describe your sock" %> </div>
    <div class="col-12 col-md-6"> <%= s.input :pattern,  collection: Sock::SOCK_PATTERN %> </div>
  <div class="w-100"></div>
    <div class="col-12 col-md-6"> <%= s.input :brand %> </div>
    <div class="col-12 col-md-6"> <%= s.input :sock_type, collection: Sock::SOCK_TYPE %>
      <button type="button" class="btn btn-outline-secondary popup" data-toggle="modal" data-target="#exampleModalCenter">More info</button>
    </div>
  <div class="w-100"></div>
    <div class="col-12 col-md-6"> <%= s.input :price , label: "how much for it?"%> </div>
    <div class="col-12 col-md-6"> <%= s.input :size, collection: Sock::SIZES %> </div>
   <div class="w-100"></div>
    <div class="col-12 col-md-6"> <%= s.input :photo %> </div>
    <div class="col-12 col-md-6"> <%= s.input :season, collection: Sock::SEASON %> </div>
  <div class="w-100"></div>
    <div class="col-12 col-md-6"> <%= s.input :photo_cache, as: :hidden %> </div>
  </div>
<div class="container edit">
  <div class="row justify-content-center">
    <%= s.submit "Post Sock", class: "col-4 create-sock"%>
      <% end %>
</div>
  </div>
</div>



<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Sock types</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= image_tag 'sock_types.jpg', height: 500, width: 450, id: "sock_types" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/socks/delete.html.erb
<h1>Socks#delete</h1>
<p>Find me in app/views/socks/delete.html.erb</p>

app/views/socks/edit.html.erb
<div class="container" style="color: #006DAA">
  <div class="row justify-content-center">
    <h1 style="margin-bottom: 1em">My Sock</h1>
      <%= render 'form' %>
      <%= link_to 'Back', sock_path(@sock), class: "back-btn btn btn-primary my-5" %>
  </div>
</div>

app/views/socks/index.html.erb
<div class="banner">
  <div class="container">
    <div class="row justify-content-between align-items-center mt-5">
      <div class="col-12 col-lg-6">
        <%= image_tag 'washer.gif', crop: :fill, id: "washer" %>
      </div>
      <div class="col-12 col-lg-6 ">
        <div class="d-flex flex-column justify-content-center">
          <h1 id="war">Don't let the washer win </h1>
          <h1 id="join">Join sockCiety! </h1>
          <br>
          <p class= "text-center">Find the match to your lost sock.</p>

        </div>
      </div>
    </div>
  </div>
</div>


<h1 style="color: #006DAA; margin-bottom:1em" id="socks_index_title">Our Socks</h1>
<br>
<div class="d-flex">
  <div class="dropdown ">
    <div>
      <h2>Filter</h2>
      <br>
    </div>
    <%= form_tag socks_path, method: :get, remote: true do %>
      <div>
        <label class="filter-label">Color</label>
      </div>
      <div>
          <%= select_tag :filter_color, options_for_select(Sock::COLOR, params[:filter_color]), prompt:"Please select"%>
      </div>
      <br>
      <br>
      <div>
        <label class="filter-label">Sock type</label>
      </div>
      <div>
        <%= select_tag :filter_sock_type, options_for_select(Sock::SOCK_TYPE, params[:filter_sock_type]), prompt:"Please select"%>
      </div>
        <br>
        <br>
      <div>
        <label class="filter-label">Sock pattern</label>
      </div>
      <div>
        <%= select_tag :filter_sock_pattern, options_for_select(Sock::SOCK_PATTERN, params[:filter_sock_pattern]), prompt:"Please select"%>
      </div>
      <br>
      <br>
      <div>
        <label class="filter-label">Season</label>
      </div>
      <div>
        <%= select_tag :filter_season, options_for_select(Sock::SEASON, params[:filter_season]), prompt:"Please select"%>
      </div>
      <br>
      <br>
      <%= submit_tag :Filter, class: 'filter-submit btn btn-primary mb-2', remote: true%>
    <% end %>
  </div>

  <div class="container card-container">
    <%= render 'cards_container', socks: @socks %>
  </div>

  <div class = "about py-5">
    <h2 class="about-header">The <strong>ultimate</strong> sock finder app</h2>
    <br id="top">
    <div class="d-flex justify-content-between align-items-top" >
      <div class="text-justify">
        <p>In <strong>SockCiety™️</strong>, we pride ourselves for giving the ultimate user experience, for the people who truly deserve it. Our community includes people from all around the world. <br> We believe that socks don't have only one sockMate, and could eventually, given the time, find a new match. That’s why we built the <strong>SockCiety™️</strong>, for sock lovers to meet, find their match and enjoy their favorite socks once more.
        </p>
      </div>
    </div>
  </div>
</div>

<%= link_to image_tag 'arrow-up.png', :anchor => "socks_index_title", class:"button", id:"btn-fixed" %>

app/views/socks/index.js.erb
// find the sock container
const cards = document.querySelector('.card-container');
// rerender it with a new @socks
cards.innerHTML = '<%= j render "cards_container", socks: @socks %>';

app/views/socks/new.html.erb
<div class="container" style="color: #006DAA">
  <div class="row justify-content-center" >
    <h1>Add a sock to SockCiety</h1>
      <%= render 'form' %>
  </div>
</div>

app/views/socks/show.html.erb
<br>
<br>

<div class="wrapper container">


  <div class="sock-container">
    <div class="row images">
      <% if @sock.photo? %>
        <%= cl_image_tag @sock.photo, height: 180, width: 280, crop: :fill, class: "col-xs-12, col-sm-6", alt: "no image" %>
      <% else %>
        <%= image_tag "demo.png", height: 180, width: 280, crop: :fill, class: "col-xs-12, col-sm-6", alt: "no image" %>
      <% end %>
    </div>
    <h3 class="filter">Your sock is</h3>
    <div class="overview-categories">
      <div class="categories-first">
        <div class="category">
          <i class="fas fa-palette"></i>
          <%= @sock.color %>
        </div>
        <div class="category">
          <i class="fas fa-hashtag"></i>
          <%= @sock.pattern %>
        </div>
        <div class="category">
          <i class="fas fa-cloud-sun"></i>
          <%= @sock.season %>
        </div>
      </div>
      <div class="categories-second">
        <div class="category">
          <i class="fas fa-shoe-prints"></i>
          <%= @sock.size %>
        </div>
        <div class="category">
          <i class="fas fa-socks"></i>
          <%= @sock.sock_type %>
        </div>
        <div class="category">
          <i class="fas fa-tag"></i>
          <%= @sock.brand %>
        </div>
      </div>
    </div>
    <div class="sock">
      <p id="user"><%= @user.username %></p>
      <h1><%= @sock.title %></h1>
      <h2><strong>$ <%= @sock.price %></strong></h2>
      <p class="desc"> <%= @sock.description %></p>
      <div class="buttons">
        <% if @sock.user == current_user %>
          <% if policy(@sock).edit? %>
            <div class="logged-in-user d-flex">
              <div id="update-button">
                <i class="fas fa-pen"></i>
                <%= link_to "Edit", edit_sock_path %>
              </div>
            </div>
          <% end %>
          <% if policy(@sock).destroy? %>
            <div id="delete-button">
              <i class="far fa-trash-alt"></i>
              <%= link_to "Delete", sock_path(@sock),id:"delete-button", method: :delete, data: { confirm: "Are you sure?" } %>
            </div>
          <% end %>
        <% else %>
          <%= link_to "Buy this sock", new_sock_transaction_path(@sock), id: "add", class: "text-center" %>
        <% end %>
      </div>
    </div>
  </div>

<div class="sock-container">
  <div id="map" style="width: 100%; height: 100%;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
</div>
</div>

<div class="review-container container">
  <%= link_to profile_path(@sock.user) do  %>
    <% if @sock.user.photo.file.nil? %>
      <%= image_tag 'sock.png', height: 40, width: 25, crop: :fill, class:'card-sock-user avatar-bordered' %>
    <% else %>
      <%= cl_image_tag @sock.user.photo, height: 40, width: 25, crop: :fill, class:'card-sock-user avatar-bordered'  %>
    <% end %>
  <% end %>
  <h2>About <%= @user.username %></h2>
  <div class="overall-rating">
    <% if @user.rating != 0 %>
      <p class="headline"><strong>User Rating: </strong></p>
      <div class="stars">
        <% @user.rating.times do%>
          <%= image_tag 'rating-sock.png' %>
        <% end %>
      </div>
      <div class="sock-reviews">
        <p class="headline"><strong>User Reviews</strong></p>
        <% @user.reviews.each_with_index do |review, index| %>
          <%reviewer = User.find(@ids[index]) %>
          <div class="sock-review">
            <div class="review-rating">
              <p class ="d-flex"><strong><%= reviewer.username %></strong>
                <%review.rating.times do %>
                  <%= image_tag 'rating-sock.png' %>
                <% end %>
              </p>
            </div>
            <div class="review-content">
              <p><%= review.description %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <%# @user.rating %>
      <p style="margin-bottom: 1em">No Reviews yet</p>
    <% end %>

    <div id="review-button">
      <i class="fas fa-edit"></i>
        <%= link_to "Add a review", new_review_path(@user.id) %>
    </div>

  </div>
</div>

app/views/socks/update.html.erb
<h1>Socks#update</h1>
<p>Find me in app/views/socks/update.html.erb</p>