config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'profile/:id', to: 'pages#profile', as:'profile'
  resources :socks do
    resources :transactions, only: [:show, :new, :create]
  end
  root to: 'socks#index'
  get "profile/:id/reviews/new", to: "reviews#new", as:"new_review"
  post "profile/:id", to: "reviews#create", as:"user_reviews"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="content">SockCiety</div>
  <div class="social-box">
    <div class="social"><i class="fab fa-facebook"></i></div>
    <div class="social"><i class="fab fa-twitter"></i></div>
    <div class="social"><i class="fab fa-google-plus-square"></i></div>
    <div class="social"><i class="fab fa-linkedin"></i></div>
    <div class="social"><i class="fab fa-dribbble-square"></i></div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-sock sticky">

  <!-- Logo -->
  <div class="navbar-sock-brand">
    <a class = "d-flex align-items-center"href="/">
      <%= image_tag "new-logo.png", {alt: "logo"}  %>
      <h2>SockCiety</h2>
    </a>
  </div>

  <div id="search_navbar"  hidden-xs hidden-sm>
    <div id="search-bar">
      <%= form_tag(root_path, :method => "get", id: "search-form",remote: true) do %>
      <%= text_field_tag :search, params[:search], placeholder: "Find your missing sock", class: "form-control" %>
      <%= button_tag(type:"submit", class:"search-icon") do %>
        <i class="fas fa-search search-icon"></i>
      <% end %>
      <% end %>
    </div>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-sock-right" hidden-md hidden-lg >

    <%  if current_user %>
        <%= link_to "Add a sock", new_sock_path, class:"navbar-sock-item navbar-sock-link" %>
      <%= link_to "My Profile", profile_path(current_user), class:"navbar-sock-item navbar-sock-link" %>
      <div class="navbar-sock-item">
        <div id="dropdown">
          <% if current_user.photo.file.nil? %>
            <%= image_tag 'avatar_ifnil.png', height: 40, width: 25, crop: :fill, class:"avatar dropdown-toggle", id:"navbar-sock-menu", data: {toggle: 'dropdown'}%>
            <% else %>
              <%= cl_image_tag current_user.photo, height: 40, width: 25, crop: :fill, class:"avatar dropdown-toggle", id:"navbar-sock-menu", data: {toggle: 'dropdown'}%>
            <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-sock-dropdown-menu">
            <li><%= link_to "Edit Account", edit_user_registration_path, class:"navbar-sock-item navbar-sock-link" %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class:"navbar-sock-item navbar-sock-link" %></li>
          </ul>
        </div>
      </div>
    <% else %>
      <button type="button" class="user btn btn-btn-outline-primary" data-toggle="modal" data-target="#login">Log In</button>
      <button type="button" class="user btn btn-btn-outline-primary" data-toggle="modal" data-target="#signup">Sign Up</button>
    <% end %>
  </div>
</div>
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="loginmodal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginmodal">Log In</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% @instance_user = User.new %>
      <%= simple_form_for(@instance_user, url: session_path(@instance_user)) do |f| %>
        <div class="form-inputs">
          <%= f.input :email,
                      required: false,
                      autofocus: true,
                      input_html: { autocomplete: "email" } %>
          <%= f.input :password,
                      required: false,
                      input_html: { autocomplete: "current-password" } %>
          <%= f.input :remember_me, as: :boolean %>
        </div>


      </div>
      <div class="modal-footer">
        <div class="form-actions">
          <%= f.button :submit, "Log in", class:"user-btn" %>
        </div>
      <% end %>

      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="signup" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Sign Up</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% @instance_user = User.new %>
        <%= simple_form_for(@instance_user, url:  registration_path(@instance_user)) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%= f.input :email,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "email" }%>
            <%= f.input :password,
                        required: true,
                        hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                        input_html: { autocomplete: "new-password" } %>
            <%= f.input :password_confirmation,
                        required: true,
                        input_html: { autocomplete: "new-password" } %>

            <%= f.input :username, label: "choose a username" %>
            <%= f.input :photo, label: "upload a picture with your favorite sock!"%>
            <%= f.input :photo_cache, as: :hidden %>
            <%= f.input :location, label: "share your location" %>
          </div>
        <div class="modal-footer">
        <div class="form-actions">
          <%= f.button :submit, "Sign up", class:"signup-btn" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>





 <!--      <%# link_to "Log in", new_user_session_path, class:"navbar-sock-item navbar-sock-link", data-toggle:"modal", data-target:"exampleModal" %> -->
      <%# link_to 'Sign up', new_user_registration_path, class:"navbar-sock-item navbar-sock-link" %>