config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'profile/:id', to: 'pages#profile', as:'profile'
  resources :socks do
    resources :transactions, only: [:show, :new, :create]
  end
  root to: 'socks#index'
  get "profile/:id/reviews/new", to: "reviews#new", as:"new_review"
  post "profile/:id", to: "reviews#create", as:"user_reviews"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_sock, only: [:new, :create]
  def new
    @transaction = Transaction.new
    authorize @transaction
  end

  def create
    @transaction = Transaction.new
    @transaction.user = current_user
    @transaction.sock = @sock
    authorize @transaction
    if @transaction.save
      @sock.bought = true
      @sock.save
    else
      render :new
    end
  end

  private

  def set_sock
    @sock = Sock.find(params[:sock_id])
    authorize @sock
  end

  def transaction_params
    params.require(:transaction).permit
  end
end

app/views/transactions/_form.html.erb
 <%= form_tag socks_path, method: :post do %>
  <p>Name on card</p>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "John doe"
  %>
<br>
  <p>Credit card number</p>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "****************"
  %>
  <br>
    <p>experation date</p>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "mm/dd"
  %>

  <br>
    <p>CVV <i class="fas fa-question-circle"></i></p>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "***"
  %>
<% end %>

<br>

app/views/transactions/create.html.erb
<div class="container" style="margin-top:10em">
  <div class="row justify-content-center" style="color: #006DAA">
    <div class="col-12 col-md-6 col-lg-4">
      <h2>Your order has been processed</h2>
      <p style="margin-top:1em">One small sock for man, one giant sock for mankind</p>
    </div>
  </div>
</div>


<div class="login-page">
  <div class="form">
    <form class="register-form">
      <input type="text" placeholder="name"/>
      <input type="password" placeholder="password"/>
      <input type="text" placeholder="email address"/>
      <button>create</button>
      <p class="message">Already registered? <a href="#">Sign In</a></p>
    </form>
    <form class="login-form">
      <input type="text" placeholder="username"/>
      <input type="password" placeholder="password"/>
      <button>login</button>
      <p class="message">Not registered? <a href="#">Create an account</a></p>
    </form>
  </div>
</div>

app/views/transactions/new.html.erb
<div class="container w-50" style="color: #006DAA">
  <div class="row flex-column justify-content-center" >
  <h1>Check out</h1>
    <%= render 'form' %>
    <button id= "sockcess", class = "btn btn-primary">Buy sock now</button>
  </div>
</div>